namespace VibeController.Core.Domain;

public enum ControllerControl
{
    A,
    B,
    X,
    Y,
    DPadUp,
    DPadDown,
    DPadLeft,
    DPadRight,
    LeftBumper,
    RightBumper,
    LeftTrigger,
    RightTrigger,
    LeftTriggerAxis,
    RightTriggerAxis,
    LeftStickButton,
    RightStickButton,
    Menu,
    View,
    LeftStickX,
    LeftStickY,
    RightStickX,
    RightStickY,
    RightStickLeft,
    RightStickRight,
    RightStickUp,
    RightStickDown,
    TouchpadX,
    TouchpadY,
    TouchpadButton,
}
